### ISSUE TITLE
Library update: Inconsistency with underline color of input fields

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#136]
The underline color the text input field is a slightly different color than what the dropdowns use in the library and I would *think* that this is a bug.

Text input underline color: #6A6E73 (this maps to the library palette color black-600)
Dropdown underline color: #8B8D8F (this doesn't seem to even be a color in the library palette)

Side by side: 
![image](https://user-images.githubusercontent.com/19824574/71678228-a78faa80-2d52-11ea-8425-7bd032a148ae.png)

**Comment by gdoyle1** [comment]
@maryshak1996 thanks for bringing this up! I just checked the code out and they both are supposed to receive Border color 200 which is actually black-500 #8A8D90. I know we had to apply shadows rather than a background color to those symbols, so they probably weren't updated as we updated colors. Making this change now!
