### ISSUE TITLE
primary light color (for dark background)

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#139]
<img width="816" alt="Screen Shot 2020-01-07 at 5 02 46 PM" src="https://user-images.githubusercontent.com/6415742/71933555-6e02d900-3170-11ea-8d52-c24b69508700.png">

The pf-global--primary-color--light-100 (#73BCF7 or blue-200) layer style isn't used anywhere in the sketch file.

On navigation dark theme, the blue highlights use pf-global--active-color--400 (#2B9AF3 or blue-300)

https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss says
$pf-global--primary-color--light-100:   $pf-color-blue-200 !default;

Where should #73BCF7 ( `pf-global--primary-color--light-100`  or blue-200) be used versus #2B9AF3 (blue-300) ?

**Comment by ajacobs21e** [comment]
@mcoker is there a variable in the code for the primary highlight color that's used in dark nav? Or is "pf-global--active-color--400" the variable name that's used?

**Comment by mcoker** [comment]
Hey @ajacobs21e, in the nav component, we use the variable `--pf-c-nav__list-link--m-current--after--BackgroundColor` as the value for the underline highlight color of the current nav link. The value of that variable in the dark theme nav is the var you referenced, `--pf-global--active-color--400`.

**Comment by ajacobs21e** [comment]
Thanks @mcoker ! 

What does "// do not use - theme colors for exceptions and defining theme" in the scss-variables doc I linked in the first post?

**Comment by mcoker** [comment]
The vars with `--pf-global--[thing]--light/dark-*` were originally created with the intent of only being used in the context of a light/dark theme, or themed component. They shouldn't be used when you just want a different shade of a color in normal use. There are some exceptions to that, but overall we follow that rule.

**Comment by ajacobs21e** [comment]
Ok thank you! So it's more about using that variable name rather than the variable value.

**Comment by mcoker** [comment]
Correct! `--pf-global--primary-color--light-100` is a lighter version of `--pf-global--primary-color--100` for use in a dark theme. So anywhere we define a dark theme in PF, `--pf-global--primary-color--100` takes on the value of `--pf-global--primary-color--light-100`.

If a patternfly user was to override `pf-global--primary-color--light-100` in their application to a slightly different shade of blue so that the dark theme version of `pf-global--primary-color--100` was this different shade of blue, if we (patternfly developers) were using `pf-global--primary-color--light-100` in some non-theme way just to apply that variable's value as a color somewhere, our improper use would result in the places we used it changing with the user's override, when their intent was only to change `pf-global--primary-color--100`'s value in a dark theme.

**Comment by ajacobs21e** [comment]
Ah ok. So here's where I'm confused. 

For example, the form input active state has an bottom border of primary blue, #06c 
`--pf-c-form-control--focus--BorderBottomColor: var(--pf-global--primary-color--100);`

In the sketch file, the dark theme form input active state border is #2B9AF3, which is not `--pf-global--primary-color--light-100`
That darker blue color looks much better IMO. 
The lighter blue is the hover state for dark theme buttons rather than the primary color. 

I'm not sure if this is an issue with the sketch file being wrong (@gina), or the visual design not being consistent (@mceledonia), or with the variable naming not being clear. 
Hopefully Michael can weigh in tomorrow from the visual side and we can figure out what, if anything, needs to be updated. Thanks @mcoker !

**Comment by ajacobs21e** [comment]
`pf-blue-200` is used on #140 
Gina will look to see where else pf-blue-200 is used and where `pf-global--primary-color--light-100` is used.

The solution may be to change the variable name (or create a new variable) for `primary-color--light` that is the primary color used for dark theme (complementary to where #0066cc would be used on a light theme).

**Comment by mceledonia** [comment]
Let's go with blue-300 for dark theme primary blue, it looks closer to our light theme primary and passes contrast. I agree we should consider changing `pf-global--primary-color--light-100` name to something else if we aren't using it in a primary way, maybe changing it to secondary?

**Comment by gdoyle1** [comment]
The variable pf-global--primary-color--light-100 isn't used anywhere as well!

**Comment by ajacobs21e** [comment]
@gdoyle1 blue-200 is the dark theme link hover color, right?

**Comment by gdoyle1** [comment]
@ajacobs21e blue-200 is used for dark theme link color, blue-300 is used for dark theme link hover color...

--pf-global--link--Color--light | $pf-global--active-color--300 | $pf-color-blue-200 | #73BCF7

--pf-global--link--Color--light--hover | $pf-global--active-color--400 | $pf-color-blue-300 | #2B9AF3

**Comment by ajacobs21e** [comment]
@gdoyle1 it's opposite in the sketch file for link buttons. Is that a mistake?

**Comment by gdoyle1** [comment]
@ajacobs21e Yes it must be a mistake! We haven't updated the dark theme stuff in forever

**Comment by ajacobs21e** [comment]
@mceledonia if this is the case (link / link button blue (#0066CC) becomes blue-200 (#73BCF7) for dark theme), then should all instances of primary blue become blue-200 for dark theme? Personally I still think blue-300 looks better but consistency rules :)


> --pf-global--link--Color--light | $pf-global--active-color--300 | $pf-color-blue-200 | #73BCF7
> 
> --pf-global--link--Color--light--hover | $pf-global--active-color--400 | $pf-color-blue-300 | #2B9AF3

**Comment by gdoyle1** [comment]
But since Michael said this "Let's go with blue-300 for dark theme primary blue, it looks closer to our light theme primary and passes contrast. I agree we should consider changing pf-global--primary-color--light-100 name to something else if we aren't using it in a primary way, maybe changing it to secondary?" - we should probably permanently make that change so that the default is blue-300 and the hover is blue-200 (which is what it is in Sketch library). And then we can make sure that all instances of blue-300 are used for primary dark theme (so where #0066cc is used in our light theme). @mceledonia @ajacobs21e Does this sound correct to you guys?

That means that the following variables would become blue-300:
1. pf-global--link--Color--light
2. pf-global--active-color--300

Which would update colors in these components:
1. Links and link buttons (dark theme) : 
2. Selectable data list expanded (default state) : --pf-c-data-list__item--m-expanded--m-selectable--before--BackgroundColor

**Comment by ajacobs21e** [comment]
Done; will update Sketch with a batch of changes
