### ISSUE TITLE
Popovers with no headers do not allow text to wrap to multiple lines

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#152]
"I’m using the Popover / 5. No Header / 1. Top component, and the issue about it is that when you paste some longer text in there it will auto-resize horizontally the symbol artboard and the content layer, but it won’t resize (wrap) the text when you custom resize the component. So currently the only to have text in multiple lines in a popover is to manually add breaks withint the text itself, not ideal."

<img width="617" alt="Screenshot 2020-01-22 17 50 48" src="https://user-images.githubusercontent.com/30870144/72924853-aa613800-3d1f-11ea-8e5d-0970ca927887.png">

**Comment by ajacobs21e** [comment]
it’s working as designed at least. We can either have the component resize horizontally OR vertically. Not both. You can manually enter a line break and stretch the component vertically. I assumed having a single line was the more common use case so chose to have them resize horizontally instead of vertically. If that assumption is incorrect, we can remake the component to wrap by default.

I will look into making a variant that resizes vertically and adding it either as a symbol or to the template file.

**Comment by cntlsn** [comment]
Hi @ajacobs21e, thank you for your comment!
PF documentation (https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#provide-the-right-kind-of-help) suggests to _"Use a popover for longer (2 sentences or more) explanations"_, and documentation found in other design systems confirm a similar approach.

I have actually created a variant of the component, leaving layout to horizontal and aligned to left, but forcing content layer alignment to vertical instead of horizontal. 
This solution is only partially correct though: as you can see in the screenshot below, after submitting the content it will overflow, but at least the component will be easily resizable. Albeit after correctly resizing the component, the content layer will look like it keeps overflowing the component artboard.
<img width="483" alt="Screenshot 2020-01-22 17 55 43" src="https://user-images.githubusercontent.com/2865173/72982212-dabbdb80-3dde-11ea-8a65-7f845503cef1.png">

What do you think? Am I taking a wrong approach here?

**Comment by ajacobs21e** [comment]
Hey @cntlsn 
This is unfortunately a case where Sketch's flexibility has limitations. We've decided to not change the symbol in the library and instead will be adding an example of a multi-line popover to the template file.

There are three workarounds you could do-
1- Detach the popover symbol and then create a local symbol that includes the bottom point of the popover within the artboard (make the artboard taller). Vertical auto resizing works that way but it also means the top & bottom popovers will be a different size from the left & right popovers and won't be interchangeable, which is why we didn't go that route in the symbol library. 

2- Add manual line breaks to the text and stretch the component vertically. That way the content layer should stay within the bounds of the component.

3- Put a space in the popover symbol component, put a separate text layer on top of the blank popover symbol, and resize the popover in either direction as necessary. 

I hope that helps! Let me know if you want me to jump on bluejeans or record a quick video to explain any of those.

**Comment by cntlsn** [comment]
Hey @ajacobs21e, thank you for the thorough explanation.
I had a feeling that I was hitting against some kind of software limitation, and now I understand why you decided to proceed with that solution to accommodate all possible spatial orientations of the component.

The workarounds make sense to me. I also think my option could work, I'm just concerned it might break with future software updates?

Anyway, thank you for now!

**Comment by gdoyle1** [comment]
We added an example of a popover with text laying over it in the template file. Will close this! Thanks @cntlsn
