### ISSUE TITLE
Line-height of text creates difficult/time-consuming spacing in Sketch library

### ISSUE THREAD

**Issue by samlinville** [patternfly/patternfly-design-kit#170]
Because the line-height of text components in PF4 is dictated by a ratio, some of the font sizes (`pf-c-breadcrumb_linkleaf` at 14px, for example) have line-heights expressed as decimal values. While this is no problem in the browser, it complicates the process of designing quickly in Sketch, when text boxes are now fractions of pixels and positioned on sub-pixel values. It's difficult to accurately calculate spacing, and it means that the vertical spacing of a UI can end up being off by several pixels by the end of a longer page. Resolving this manually becomes very time-consuming.

<img width="239" alt="Screen Shot 2020-02-21 at 10 12 41 AM" src="https://user-images.githubusercontent.com/3967272/75051017-bbbe7100-5492-11ea-9696-ddd71433d756.png">

<img width="514" alt="Screen Shot 2020-02-21 at 10 15 25 AM" src="https://user-images.githubusercontent.com/3967272/75051292-38514f80-5493-11ea-8929-a240e9ce7459.png">

Is there a way that we could adjust this so that the Sketch library ends up with whole pixel values for line-height?

cc @gdoyle1

**Comment by gdoyle1** [comment]
Hi @samlinville I wanted to let you know that I spoke with Michael and Kyle and we agreed that it's best to leave the line heights as they are. It'll cause a lot of confusion for designers who hand off these to devs and the line height is off which will most likely cause the rest of the design to be off spacing-wise.

I do have some solutions for quick spacing tips here that I always use (even with those weird line height type styles) - hopefully this helps your workflow! I worked on the colors page for the PF site and the title sizes I was using have decimals in their line heights. I used the "tidy" feature to space the rest of my elements out on the page above/below it and I had no problem with elements on sub-pixels or spacing shown as sub-pixel values.
<img width="1082" alt="Screen Shot 2020-04-06 at 9 33 02 AM" src="https://user-images.githubusercontent.com/30870144/78563998-d00fc080-77e9-11ea-9888-5c25d5ab0cd5.png">
Not sure if you already knew about this feature but it's great in general to determine horizontal or vertical space between elements on the page!

For now, I'm going to close this issue since we won't be changing the library.
