### ISSUE TITLE
Inline edit in table

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#172]
Add a template example of inline edit in a table. We should have all the symbols available for this.

Here's a flow to use as reference: https://www.patternfly.org/v4/documentation/react/components/table#editable-rows

**Comment by maryshak1996** [comment]
I created this (screenshot below) for now since this is all that's been implemented, but I can add more once it moves out of a beta state. There's a few things in the implementation that are inconsistent with the design docs for it, so I'm curious which is what we should be representing in the template. 
<img width="908" alt="Screen Shot 2020-03-27 at 11 18 27 AM" src="https://user-images.githubusercontent.com/19824574/77771455-13fe0b00-701d-11ea-89a8-8ab521ee042a.png">

But for now, here's a template that represents what's been implemented at this point:
[inline-edit-table_template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4394355/inline-edit-table_template.sketch.zip)

**Comment by gdoyle1** [comment]
I think this is a great start for this and we can create more as more is implemented @maryshak1996 . Going to merge this into the template file. Thank you!

Closing this
