### ISSUE TITLE
Template: Notification Drawer

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#213]
Using the Notification Drawer symbols:
1. Add an artboard titled "Spec" (see other pages in template file for examples) and unhide the padding groups for Notification Drawer/Group , Notification Drawer/Header ,  and Notification Drawer/Notification symbols
2. Recreate the mockups used [here](https://www.sketch.com/s/dc94bff0-6fb3-42b8-90f6-a2d6ba9dcfee) and add them as individual artboards to the "Notification Drawer" page in the template file

**Comment by mcarrano** [comment]
@gdoyle1 Here are the notification drawer mockups I had. I tried to clean these up as much as possible and name some of the layers, although it's still pretty messy. Not sure if there is a way you like to organize the template files to make them easy to modify. Let me know whether this needs more work or if there's something else I need to do.

Sketch Cloud link: https://www.sketch.com/s/dc94bff0-6fb3-42b8-90f6-a2d6ba9dcfee/v/y9x5dy

**Comment by gdoyle1** [comment]
@mcarrano Thanks to Laura, we now have up-to-date notification drawer symbols in the library! Would you want to take another stab at this issue? I have created a "Notification Drawer" page in the template file where we can add the spec on the first artboard (the spacers of the symbols would be visible) and then in following artboards, you'd recreate the examples that you had put together in the Sketch file above so that they are using the symbols instead!

**Comment by mcarrano** [comment]
Sure. I can take this @gdoyle1 .

**Comment by gdoyle1** [comment]
As discussed through Slack, merged the correct template!

For reference, sketch cloud link: https://www.sketch.com/s/a62058a7-bc68-4965-90e3-958576206ff4/p/notification-drawer
