### ISSUE TITLE
Customizable alert symbol

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#250]
Create a version of an alert (both inline and toast) called `custom` where the user can override the following:
1. Status bar color (bar on the left)
2. Icon type
3. Icon color

**Be sure to** add a PRE-RELEASE label to these symbols (see separator symbols for example)

**Comment by doruskova** [comment]
@gdoyle1 I know we didn't discuss this issue at all, I just wanted to play with Sketch symbols and learn how it works. So, it's up to you if it's useful, haha. 

<img width="986" alt="Snímek obrazovky 2020-09-03 v 15 10 10" src="https://user-images.githubusercontent.com/32618096/92120424-552eee00-edf9-11ea-88e5-760a4a577d35.png">

The status bar, icon type, icon color are customizable for toast and inline. But, I think that the inline background color should be customizable too because then it doesn't match together with the status bar. 

Here's the sketch file 
[alerts-custom.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5168777/alerts-custom.sketch.zip)

**Comment by gdoyle1** [comment]
Great idea!!! I think we should do that as well. I checked out the sketch file and I would make sure you're pulling a blue label from the `document symbols` once more. I think I must've merged something that added another blue label in somehow. I _just updated the library_ so you should be good to go to copy these over to the newest doc and add the Document Blue labels in!

**Comment by doruskova** [comment]
It should be ok now :) [PatternFly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5169478/PatternFly.sketch.zip)
