### ISSUE TITLE
Table template example text wrapping

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#287]
https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89/a/Ao8nGz
The text in the donut accidentally wrapped

**Comment by doruskova** [comment]
@ajacobs21e I took a look at it and it needs to be a bug on a Sketch Cloud ([issue](https://www.reddit.com/r/sketchapp/comments/e5llrz/cloud_doesnt_match_the_sketch_file/?utm_source=share&utm_medium=web2x&context=3)) because it looks ok when I downloaded the template. Ehm.. weird. Let me know if you saw it in a template. This is how it looks in a template. 
![Expandable - desktop](https://user-images.githubusercontent.com/32618096/94792085-c81b8c80-03d8-11eb-8cca-2490b8ca56b0.png)

It's everywhere on a cloud. :////
<img width="986" alt="Snímek obrazovky 2020-10-01 v 11 30 08" src="https://user-images.githubusercontent.com/32618096/94792600-7d4e4480-03d9-11eb-9394-a5a9e545528b.png">

**Comment by doruskova** [comment]
@ajacobs21e I checked it again and it looks that they fixed it. It looks normal. YAY :)
