### ISSUE TITLE
Splitter demo

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#315]

**Comment by doruskova** [comment]
@maryshak1996 Would you mind taking this issue? I know you've been working on it, but if you don't want to do it, just let me know :) Also, it's possible that the symbol will need a change (background color) too.

**Comment by maryshak1996** [comment]
@doruskova sure, I'll take this!

**Comment by doruskova** [comment]
Thank you!

**Comment by maryshak1996** [comment]
@doruskova I put together three template examples here :) 
I checked the background color of the splitter demo against what's been implemented and it looks to be correct.
I didn't include a spec artboard because there's nothing to really be aware of with the spacing of the splitter itself. If you want me to do a spec in some other way, let me know!
[patternfly-template_splitter-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5538290/patternfly-template_splitter-template.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 Merged! 
That's totally fine, the spec wouldn't make sense in this case.
