### ISSUE TITLE
Text with unintentional stroke

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#332]
I noticed that the focus state for the text input component has a grey stroke on it, which is definitely not intentional (shown below)
<img width="1217" alt="Screen Shot 2021-01-19 at 3 25 22 PM" src="https://user-images.githubusercontent.com/19824574/105089003-95220500-5a6a-11eb-8b45-7ef3d78fb58a.png">
I didn't dig deep into this yet to see if this is an accidental stroke applied to that whole text variable, or if it was accidentally applied just to that symbol though, so I'm not sure if this affects other things or not.

**Comment by doruskova** [comment]
Yeah, I think that the focus state needs to be updated in general because usually, it's just the blue rounded border around the input. It doesn't have a lighter background around it. I'll take a look at it and fix it :) 
<img width="850" alt="Snímek obrazovky 2021-01-20 v 11 30 19" src="https://user-images.githubusercontent.com/32618096/105162499-fbfaf900-5b12-11eb-8e8a-3cc6275d7278.png">

**Comment by doruskova** [comment]
@maryshak1996 I think it was just a bug and it's fixed now. There was a border for no reason. But, I'll open an issue for the redesign of the focus state. 
![Snímek obrazovky 2021-01-21 v 16 02 44](https://user-images.githubusercontent.com/32618096/105368804-2f688100-5c02-11eb-9be7-92f1cd98db09.png)
