### ISSUE TITLE
Symbol library: Datepicker

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#36]

**Comment by doruskova** [comment]
@gdoyle1 Do we have any React/Core issue related to this? Why is it on hold?

**Comment by gdoyle1** [comment]
@doruskova I think they are in the process of adding it to React - it's on hold to figure out what the design will be based on their implementation! I would continue to keep this on hold since lots of designers are looking for this and adding it to the symbol library will probably lead them to believe the component is available

**Comment by doruskova** [comment]
PF basic date picker available [here](https://www.patternfly.org/v4/components/date-picker/react)
@gdoyle1 I think we can remove "on hold" label. WDYT?

**Comment by gdoyle1** [comment]
@doruskova Agreed!
