### ISSUE TITLE
Add search input with submit button

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#382]
Add new variant of search input with submit button to a template file 
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563653831363532346536633539346463316230646634642f31663139393162642d613261662d343733372d623536622d343132316665326363316266](https://user-images.githubusercontent.com/32618096/116985911-68b68f80-accd-11eb-9f62-d95a7911afa0.png)

**Comment by jhiadlov** [comment]
[Search input.zip](https://github.com/patternfly/patternfly-design-kit/files/6488890/Search.input.zip)
Done. I added it into the Search input spec plus I made a new artboard with search input with explicit submit button. I deleted the blue Action button because I assumed it is not necessary anymore. But I can add it back if you say so 😄

**Comment by doruskova** [comment]
@jhiadlov Looks great! However, could you use symbols in the artboard? I'll show you what I mean in our 1:1 :)

**Comment by jhiadlov** [comment]
[search.zip](https://github.com/patternfly/patternfly-design-kit/files/6492873/search.zip)
changed to symbol

**Comment by doruskova** [comment]
@jhiadlov Can you fix the icon inside of the icon field? There should be an arrow. 
![Snímek obrazovky 2021-05-17 v 13 48 50](https://user-images.githubusercontent.com/32618096/118483750-b17f3700-b716-11eb-9056-b95d2800a97a.png)

**Comment by jhiadlov** [comment]
[search.zip](https://github.com/patternfly/patternfly-design-kit/files/6499023/search.zip)

**Comment by doruskova** [comment]
@jhiadlov Merged!
