### ISSUE TITLE
plain alert

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#412]
https://github.com/patternfly/patternfly/issues/4220

@doruskova do you have the original Marvel designs for this? https://marvelapp.com/prototype/852jaj9/screen/75866265

**Comment by doruskova** [comment]
@ajacobs21e Hey! Sending a sketch file for it. It's a little bit different and eventually, we didn't need it because we didn't have a mechanism for how to recognize that an issue has been resolved.
[simple_alert.zip](https://github.com/patternfly/patternfly-design-kit/files/6929557/simple_alert.zip)

**Comment by ajacobs21e** [comment]
[simple_alert.zip](https://github.com/patternfly/patternfly-design-kit/files/6933459/simple_alert.zip)
here are the symbols. should we wait for these to be merged into the main branch first?

note to also check on the custom alert symbols - it looks like not all of them had title text style override checked so that text can't be customized.

**Comment by doruskova** [comment]
@ajacobs21e Yeah! I'd wait for it. Also, I'm assuming that we'll need plain warning, danger etc, right? 
Oohh, ok. I'll check the custom alerts.

**Comment by doruskova** [comment]
@ajacobs21e Symbols merged!

**Comment by doruskova** [comment]
Example merged!
