### ISSUE TITLE
Allow all style overrides in the library

### ISSUE THREAD

**Issue by neanda** [patternfly/patternfly-design-kit#470]
In some symbols, it'd be very useful to change the Text Style to be bold (like for Cards) or centred (like in Masthead tabs, or to generally change Layer Styles.  Allowing all styles to be overriden, by default, would allow for more flexibility in using the PF Design System (which is, by the way, the most well-thought out and comprehensive one out there, thank you your detailed work on this and for making this available :).

Every time I update to the latest library, I have to go into it and Allow Text and Layer styles for numerous symbols, I just think it would allow for more customisability of the design system if it was all allowed by defualt (rather than turning them off in places), it wouldn't alter the design in any way, rather, it would make it more applicable to different use cases / branding etc. This kind of flexibility would make this Design System even more useful to a wider audience.  Thank you

**Comment by neanda** [comment]
I see what you mean, but if PF is meant as a DS for anybody else (as I realise the Red Hat DS is for only RH apps), shouldn't it be free to adjust to our own patterns, after starting from PF?

**Comment by doruskova** [comment]
@neanda I'll consider it. Currently, many components have all overrides enabled (cards). The next option is that you can always detach the symbol from the library and customize it as needed. When I enable overrides, for instance, for text styles now > the library needs to be prepared for that because it's possible that you'll not find what you need at the moment. We'll work to make it make sense https://github.com/patternfly/patternfly-design-kit/issues/475

cc @mcarrano
