### ISSUE TITLE
Library update: Form spacing

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#48]
- Deleted deprecated stacked & inline form components
- Updated the spacing for the vertical and horizontal aligned forms
@mceledonia can you confirm this is correct please? I'm not sure if for the horizontal the 150px label includes the required star too (I have it within that 150px box)
![Screen Shot 2019-07-01 at 2 24 25 PM](https://user-images.githubusercontent.com/6415742/60461010-54a63080-9c13-11e9-8a12-efc8021368eb.png)

![Screen Shot 2019-07-01 at 3 38 14 PM](https://user-images.githubusercontent.com/6415742/60462123-76ed7d80-9c16-11e9-8acf-819321c1c70d.png)

- Reset the size of the input field so that it picks up forms + dropdowns as overrides

- Deleted Dropdowns / 1. Toggle / Groups 
-- redundant with Dropdowns / 1. Toggle / Select
- Deleted Dropdowns / 1. Toggle / Top / Default
-- redundant with Dropdowns / 1. Toggle / Default
- Renamed Dropdowns / 1. Toggle / Top / Expanded to Dropdowns / 1. Toggle / Expanded

- Resized dark dropdowns so they can be an override of their light theme counterparts
- Added dark dropdown / expanded

[formspacing.zip](https://github.com/patternfly/patternfly-design-kit/files/3347118/formspacing.zip)

**Comment by mmenestr** [comment]
I was working on forms too and I realized that the yellow padding is wrong on the top one, it should actually be green and I changed it on my end but @gdoyle1 just bringing this to your attention when you merge because it might be a little confusing. Will probably need to revisit it tomorrow to make sure the symbol ends up with all the proper changes, but for now maybe just merge Allie's versions of those two screenshotted symbols and not mine :)

**Comment by ajacobs21e** [comment]
Thanks @mmenestr ! Sorry I didn't mean to step on your work, but of course trying to make one small change lead to this whole issue :)

**Comment by gdoyle1** [comment]
Merged!
