### ISSUE TITLE
Bug: labels don't resize properly

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#504]
The label outlines aren't getting "pinned" properly I guess, so they look like this, which makes it so that we have to manually expand the width to make it look normal

![image](https://user-images.githubusercontent.com/51165119/152433026-5fc6303e-729f-4136-ba8e-91de0b63aca1.png)

@doruskova

**Comment by doruskova** [comment]
@mmenestr Unfortunately, this is how it works in Sketch. Let me explain it because I discussed this issue with a Sketch team. 
Labels are using a Smart layout. That means you can't resize these components manually. Using Smart Layout and manually resizing elements might behave unexpectedly causes it isn't the intended purpose of the feature in this case.
You can fix it with resizing icon on the right panel. So, just remember: don't resize these labels manually! If you want to switch between two labels and keep the original size, please uncheck the "Swap at Original Size" checkbox that appears when displaying the Symbol Swap menu.

<img width="807" alt="Snímek obrazovky 2022-02-04 v 9 50 31" src="https://user-images.githubusercontent.com/32618096/152499845-bdd82a0d-0357-4aa2-952c-e0a395b44550.png">


When it comes to this thing: Why is it so long??? It's because there is a hidden symbol. There should be a "close" icon. But, you selected "No symbol" for this case. The Sketch didn't do it previously. But, now... 
I opened an issue for these labels to create default labels and dismissable separately because this is annoying. #505 
<img width="499" alt="Snímek obrazovky 2022-02-04 v 9 53 41" src="https://user-images.githubusercontent.com/32618096/152500178-085a51da-b5c2-4bc8-bdca-fd3d5280202f.png">

I hope it helped a little bit.
