### ISSUE TITLE
It may lead confusion that part of the mid-fi components are colored and others are not

### ISSUE THREAD

**Issue by yih-wang** [patternfly/patternfly-design-kit#520]
Hey @cntlsn, I'm trying out the wireframe design kit and it looks really nice! There's a problem I met that the toggle of ON status is not in the blue color. I can understand that it could reduce the influence of the visual effect. But at the same time, the primary button is still with blue color. When I have both these two elements on one page, I feel like I can tell the status from the color so the toggle is in the Off status, but it actually is ON. I prefer to have all the components dropping the visual effects together or all not.

BTW, I don't have access to the right column (editing assignees, labels, projects, etc.). Guess that's because I'm not a member of this repo.

**Comment by cntlsn** [comment]
Hi @yih-wang, thank you very much for your feedback! We're glad that you find the wireframe design kit helpful!

You make a very interesting point about the colored mid-fi components. The rationale for colored mid-fi components is that we wanted to only highlight the main CTAs, in order to:
* give it special relevance
* do not overload the wireframe with visual information

In fact, we suggest keeping wireframes as lightweight as possible in terms of quantity and variety of visual information, so that:
* stakeholders are not distracted by unnecessary information when reviewing the designs, and can center their feedback on the most important aspects of the wireframe
* they are quicker to pull together for designers

That said, let me please ask you a couple of questions to better understand your issue:
* Is the toggle the main CTA in your design?
* Do you feel like it's hard for a reviewer to understand that the toggle is on its ON state?




ps: thank you also for the feedback on the creation of the issue, we will iterate the Getting started documentation accordingly!

**Comment by yih-wang** [comment]
@cntlsn Thanks for the reply!

> Is the toggle the main CTA in your design?
No, it's just one of the settings.

> Do you feel like it's hard for a reviewer to understand that the toggle is on its ON state?
I haven't showed it to the reviewer yet. But I kind of have this feeling when seeing the screen.

**Comment by aprilma419** [comment]
<img width="488" alt="Screen Shot 2022-03-15 at 8 39 10 PM" src="https://user-images.githubusercontent.com/44431015/158379757-c7142b2d-3275-442f-a9d3-3610adcf1e7d.png">

@yih-wang We looked at the design as above, according to the comments we found in the slides probably what’s needed is that the wireframe will be moved to hi-fi. That being said, feel free to use a hi-fi lib component in a wireframe if strictly necessary!

cc @cntlsn

**Comment by haley666** [comment]
That sounds great, thanks!

**Comment by yih-wang** [comment]
That sounds great, thanks!
