### ISSUE TITLE
Consistent naming of variable instances (e.g. close button)

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#93]
Alerts use the symbol name "Button / 6. Icon button / Default" for the close button. This is the name shown in overrides. 

Should we go through the library and rename variables to something more meaningful? Such as "close button" in this instance?

@cshinn @gdoyle1 what are your thoughts? This is busywork but I can take it on for my many hours of upcoming plane travel.

**Comment by gdoyle1** [comment]
@ajacobs21e If we did that we may want to then also change the names of icons so they are more meaningful and explain the use of them not just the font awesome name... but that could get tricky. I also think in this specific instance the rename isn't necessary since that is just the default icon button but then you can apply an icon in there as a button

**Comment by gdoyle1** [comment]
Closing this - may reopen in the future if we need to come back
